In [1]:
import numpy as np

In [2]:
x1 = np.array([-1.58, 0.91, -0.73, -4.22, 4.19, -0.33])
x2 = np.array([-2.01, 3.98, 4.00, 1.16, -2.02, 2.15])

x = np.vstack((x1, x2)).T
x

array([[-1.58, -2.01],
       [ 0.91,  3.98],
       [-0.73,  4.  ],
       [-4.22,  1.16],
       [ 4.19, -2.02],
       [-0.33,  2.15]])

In [3]:
# Mid range of x1
x1_midrange = (x1.max() + x1.min())/2
x1_midrange

-0.01499999999999968

In [4]:
def get_mid_range(data, column=0):
    """ Get midrange of data by column
    - x1: column=0
    - x2: column=1
    """
    midrange = (data[:, column].max() + data[:, column].min())/2
    return midrange      

def split_by(x, value, column=0):
    """ Split x array by value and column
    - x1: column=0
    - x2: column=1
    """
    split1 = x[x[:, column] <= value]
    split2 = x[x[:, column] > value]
    return split1, split2

In [5]:
x1_midrange = get_mid_range(x)
x1_split1, x1_split2 = split_by(x, x1_midrange)

# Split values of x1
x1_split1

array([[-1.58, -2.01],
       [-0.73,  4.  ],
       [-4.22,  1.16],
       [-0.33,  2.15]])

In [6]:
# Split values of x1
x1_split2

array([[ 0.91,  3.98],
       [ 4.19, -2.02]])

In [7]:
# Mid range of x2 for the 1st split
# x1_split1_x2_midrange = (x1_split1[:, 1].max() + x1_split1[:, 1].min())/2
x1_split1_x2_midrange = get_mid_range(x1_split1, column=1)

x1_split1_x2_midrange

0.9950000000000001

In [10]:
# # Mid range of x2 for 2nd split
x1_split2_x2_midrange = get_mid_range(x1_split2, column=1)

print(x1_split2_x2_midrange)
x1_split1_x2_split1, x1_split1_x2_split2 = split_by(x1_split1, x1_split2_x2_midrange, column=1)
x1_split1_x2_split1

0.98


array([[-1.58, -2.01]])

In [11]:
x1_split1_x2_split2

array([[-0.73,  4.  ],
       [-4.22,  1.16],
       [-0.33,  2.15]])

In [12]:
x1_split1_x2_split2_midrange = get_mid_range(x1_split1_x2_split2, column=1)
x1_split1_x2_split2_midrange

2.58

In [13]:

x1_split1_x2_split2_x2_split1, x1_split1_x2_split2_x2_split2 = split_by(x1_split1_x2_split2, 
                                                                        x1_split1_x2_split2_midrange, 
                                                                        column=1)
x1_split1_x2_split2_x2_split1
# Continue to split

array([[-4.22,  1.16],
       [-0.33,  2.15]])

In [14]:
x1_split1_x2_split2_x2_split1_midrange = get_mid_range(x1_split1_x2_split2_x2_split1, column=1)
x1_split1_x2_split2_x2_split1_midrange

1.6549999999999998